# Runs benchmarks.

on:
  pull_request:
  # TODO: Disabled temporarily for https://github.com/CodSpeedHQ/runner/issues/55
  # merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  BASELINE: base
  SEED: reth

name: bench
jobs:
  codspeed:
    runs-on:
      group: Reth
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: dtolnay/rust-toolchain@6d9817901c499d6b02debbb57edb38d33daa680b # stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          cache-on-failure: true
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@073d46cba2cde38f6698c798566c1b3e24feeb44 # v2.62.67
        with:
          tool: cargo-codspeed
      - name: Build the benchmark target(s)
        run: ./.github/scripts/codspeed-build.sh
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@346a2d8a8d9d38909abd0bc3d23f773110f076ad # v4.4.1
        with:
          run: cargo codspeed run --workspace
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
