# Runs benchmarks.

on:
  pull_request:
  # TODO: Disabled temporarily for https://github.com/CodSpeedHQ/runner/issues/55
  # merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  BASELINE: base
  SEED: reth

name: bench
jobs:
  codspeed:
    runs-on:
      group: Reth
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          cache-on-failure: true
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@f176c07a0a40cbfdd08ee9aa8bf1655701d11e69 # v2.67.25
        with:
          tool: cargo-codspeed
      - name: Build the benchmark target(s)
        run: ./.github/scripts/codspeed-build.sh
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@9a74b6ba663684052277e8f342b5eb99c7442a03 # v4.10.5
        with:
          run: cargo codspeed run --workspace
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
