# This workflow auto-publishes Reth to external package managers such as
# Homebrew when a release is published.

name: release externally

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@3428a0601bba3173ec0bdcc945be23fa27aa4c31 # v5
        with:
          token: ${{ secrets.HOMEBREW }}
          no_fork: true
          tap: paradigmxyz/brew
          formula: reth
