# Windows build

name: windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  check-reth:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          target: x86_64-pc-windows-gnu
      - uses: taiki-e/install-action@ba5c39e5746400f693c774054773a05493f7af20 # cross
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          cache-on-failure: true
      - name: mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Check Reth
        run: cargo check --target x86_64-pc-windows-gnu

  check-op-reth:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          target: x86_64-pc-windows-gnu
      - uses: taiki-e/install-action@ba5c39e5746400f693c774054773a05493f7af20 # cross
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          cache-on-failure: true
      - name: mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Check OP-Reth
        run: cargo check -p op-reth --target x86_64-pc-windows-gnu
